%YAML 1.1
---
# cSpell:disable

dirs:
  eng_jobs    : &eng_jobs   \\hssieng\DATA\HS\JOBS
  workorders  : &workorders \\HSSIENG\DATA\HS\SAP - Material Master_BOM\SigmaNest Work Orders
  simtrans    : &simtrans   \\hssieng\SNData\SimTrans
  tagschedule : &tagsched   \\hssfileserv1\HSSShared\HSSI Lean\CAD-CAM\TagSchedule
  sndata_prd  : &sndata_prd \\hssieng\HSSEDSSERV\SNData91
  sndata_dev  : &sndata_dev \\hssieng\SNData\SN_TESTING\SNDATA

files:
  workorder_template:
    - *workorders
    - Template_HD_new.xls
  simtrans_import_util:
    - *simtrans
    - ProductionDemand_New2.xls
  xml_import_exec:
    - *sndata_prd
    - OYS\ProgramFiles\SNImportXML\SNImportXML.exe
  flg_data_exec: \\HSSIENG\Resources\HS\PROG\FlgXlsData.exe


databases:
  sn_prd:
    server: hiiwinbl18
    database: SNDBase91
  sn_dev:
    server: hiiwinbl5
    database: SNDBaseDev

regex:
  web_or_flg    : "[0-9]{7}[A-Z]-[A-Z]{1,2}[0-9]+[A-Z]+-[WTB][NF]?[0-9]+"
  job_shipment  : "([0-9]{7})[a-zA-Z]?-([0-9]+)"

# cSpell:enable